### ISSUE TITLE
Every message has KeyError: 'encrypted'

### ISSUE THREAD

**Issue by JSmaler** [BuStudios/StashConnect#3]
Once again, I am presenting an issue which may not be StashConnect's fault.

Since the issue occurs with older versions of StashConnect, as well as my own code, or the example code, so I *assume* this is Stachcat changing something that stash connect can't cope with.

Any time I try to access any chat-message, StashConnect errors out.

My trimmed down example code (minimal way to recreate the issue):

```
import stashconnect

# without proxy / cert
client = stashconnect.Client(
    email="[my mail]", password="[my password]",
    encryption_password="[my encryption password]"
)
# get the last 30 messages of a chat
last_messages = client.messages.get_messages("[Chat ID]")
for message in last_messages:
    print(message.content)
```
run to get the following error:

```
python file.py
 
Logged in as [name]!
Importing private key. Please wait...
Traceback (most recent call last):
  File "/home/jkr/Downloads/file.py", line 14, in <module>
    for message in last_messages:
                   ^^^^^^^^^^^^^
  File "/home/jkr/.local/lib/python3.12/site-packages/stashconnect/messages.py", line 262, in get_messages
    yield Message(self.client, message)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jkr/.local/lib/python3.12/site-packages/stashconnect/models.py", line 47, in __init__
    self._decrypt_location(data["location"])
  File "/home/jkr/.local/lib/python3.12/site-packages/stashconnect/models.py", line 53, in _decrypt_location
    if location["encrypted"]:
       ~~~~~~~~^^^^^^^^^^^^^
KeyError: 'encrypted'

```

I have tried re-Installing, installing different versions of, manually installing StashConnect, I have trimmed my code to the example above, which is just the example code, cut down to only the retrieval of messages. I have confirmed this code does connect to StashConnect.

**Comment by BuStudios** [comment]
Thanks for submitting the issue! I just tried it myself and i get the same issue. I think its because of an update to how locations are handeled by Stashcat. I'll try to resolve the issue as quickly as possible.

**Comment by BuStudios** [comment]
Should be fixed. I uploaded a new version to pypi.
